# Conclusions

As a whole, the data indicate a general stability to the \textgreek{οι}/\textgreek{υ} and \textgreek{η}/\textgreek{ᾱ} isoglosses between the 4th and 2nd centuries BCE. The evidence suggests that Tanagrans had largely monophthongized \textgreek{οι} into \textgreek{υ} by the 4th cent., then retained that feature through the 2nd. This change does not appear to a statistically significant degree in any of the other cities included in this survey, as shown through the use of Fisher's exact test whenever applicable. Therefore, the data characterizes the \textgreek{οι} \> \textgreek{υ} monophthongization as a uniquely Boiotian feature within the region and periods of interest, largely in keeping with Dosuna's description of the dialect.[@dosuna2015a, 469]

The evidence also establishes the geographical extent of the Attic-Ionic \textgreek{ᾱ} \> \textgreek{η} vowel shift on the mainland of central Greece. The shift stopped after Eleusis, never making gains throughout the Doric-speaking cities of Megara, Pagai, or Aigosthena. However, the shift did spread into Boiotia as far as Oropos. The data shows that the majority of Oropians not only resisted the \textgreek{οι} \> \textgreek{υ} monophthongization but also accepted the \textgreek{ᾱ} \> \textgreek{η} raising as far back as, or possibly before, the 4th cent.\ BCE, despite the city's membership in the Boiotian League -- an association explicitly mentioned in 26 separate 3rd cent.\ Oropian inscriptions via the phrase \textgreek{κοινῶι} \textgreek{Βοιωτῶν} 'in/for the League of the Boiotians.' Nevertheless, the shift stopped with Oropos, with no evidence suggesting that it spread to Tanagra during the periods of interest. These findings agree with Panayotou's description of the dialect.[@Panayotou_2015, 410]

However, though these results are encouraging, the selection method for exemplary inscriptions lacked rigor. In order to ensure that the phonological context of a target segment remained intact, the author searched for evidence of a change within its environment: rather than testing any instance of \textgreek{η} against any instance of \textgreek{ᾱ}, the author built the data sets around complete words such as \textgreek{δᾶμος} 'deme' or \textgreek{βουλή} 'council.' To facilitate this, the author compiled a set of exemplary tokens appearing in a "non-Attic" form within the DGE, selecting for frequency under the assumption that they would remain proportionally common within the test data. Yet, given the strict measures taken when compiling the test data, as well as the heavy fragmentation of the collected inscriptions, the final subsets used for the inter-city tests were much smaller than anticipated. In addition to this, in selecting primarily for frequency, the author excluded usable data such as the o-stem endings in \textgreek{τοῖς} \textgreek{ἄλλοις} \textgreek{πρόξενοις} 'for the other public friends' from DGE 161 = IG VII 208 and the \textipa{\=a}-stem endings in \textgreek{ἀγαθᾶι} \textgreek{τύχαι} 'to good fortune' from DGE 154 = IG VII 1. Therefore, follow-up surveys should apply a more systematic method for determining which tokens to collect for testing. To use the singular \textipa{\=a}-stem endings again: the \textgreek{ᾱ}-type and \textgreek{η}-type endings can be translated into Regular Expression as `[ηα][ςσιν]{0,1}$` then appended onto any stem. For example, searching for `^αγαθ[ηα][ςσιν]{0,1}$` would then return every instance of the noun \textgreek{ἀγαθή}/\textgreek{ἀγαθά} in the singular, regardless of case, while performing a more general search for `^w*[ηα][ςσιν]{0,1}$` would return any singular \textipa{\=a}-stem noun in the corpus. The resulting data set would be more comprehensive, thereby better representing the evidence and improving the statistical power of the tests performed.
