---
format:
  pdf :
    documentclass: report
    fontsize: 12pt
    classoption: notitlepage, twoside
    indent: true
    geometry:
      - width=8.5in
      - height=11in
      - left=1in
      - right=1in
      - top=1in
      - bottom=1.25in
      - showframe=FALSE
    monofont: DejaVu Sans Mono
    df-print: kable
    fig-cap-location: top
    highlight-style: github
    include-in-header:
      - metafiles/header.tex
execute:
  echo: FALSE
  warning: FALSE
knitr:
  opts_chunk: 
    dev: "ragg_png"
editor: visual
bibliography: references.bib
csl: metafiles/chicago-fullnote-bibliography-short-title-subsequent.csl
nocite: |
  @*
---

```{=tex}
% Title and Author Settings ======================================= %
\newcommand{\doctitle}{\textgreek{κὴ γᾶς κὴ ϝυκίας}:\\
A Computer Assisted Epigraphic Study of the Isoglosses of Central Greece}
\newcommand{\docauthor}{Thomas W.  Broadwater}


%--------------------------ABSTRACT---------------------------%
\input{metafiles/abstractpage.tex}
\makeabstract{%
Given the predominance of Attic-Ionic Greek in classical Greek literature, this dialect has long been treated as representative of the language as a whole. However, epigraphic evidence depicts a more varied landscape throughout the wider Hellenic world. Modern statistical and quantitative methods enable the dialectologist to not only survey large amounts of epigraphical data but also to quantify their confidence in their results. In this initial survey, the author demonstrates a programmatic method for the development and management of an inscriptional data set, and applies that set to the study of two isoglosses in Central Greece between the 4\super{th} and 2\super{nd} centuries BCE. The author shows that the \textgreek{οι}/\textgreek{υ} and \textgreek{η}/\textgreek{ᾱ} isoglosses remained largely stable during the period of interest.
}%


%--------------------------TITLE PAGE---------------------------%
\input{metafiles/titlepage.tex}
\newcommand{\degreesearned}{%
B.A., University of Mary Washington, 2018\\
}%

\newcommand{\degreetype}{Thesis}
\newcommand{\degreetitle}{Master}
\newcommand{\degreename}{Arts}
\newcommand{\degreeyear}{2023}
\maketitlepage

%--------------------------COPYRIGHT---------------------------%
\input{metafiles/copyright.tex}
\makecopyright{2023}


%--------------------------APPROVAL---------------------------%
\newpage
\thispagestyle{empty}
\vspace*{18pt}
\begin{center}
  \textsc{\doctitle}\\[18pt]
  by\\[18pt]
  \textsc{\docauthor}
\end{center}
\vfill

\begin{flushright}
  \begin{tabular}{ll}
    Major Professor: & Jared S. Klein \\ [8pt]
    Committee: & Jordan Pickett \\
    & Charles Platter \\
  \end{tabular}
\end{flushright}

\vspace*{3cm}

\begin{flushleft}
  Electronic Version Approved:\\[12pt]
  Ron Walcott\\
  Dean of the Graduate School\\
  The University of Georgia\\
  May 2023
\end{flushleft}
\vspace*{1.5cm}

% Dedication ====================================================== %
\subfile{subfiles/dedication}

% Acknowledgements ================================================ %
\subfile{subfiles/acknowledgements}

% Table of Contents =============================================== %
\setcounter{tocdepth}{1}
\tableofcontents

\iffigures
\addcontentsline{toc}{chapter}{\listfigurename}
\listoffigures
\fi

\iftables
\addcontentsline{toc}{chapter}{\listtablename}
\listoftables
\fi

\clearpage
\pagenumbering{arabic}
```
```{r Packages}
library(dplyr)    # . For %>%, filter(), etc
library(stringr)  # . For str_detect()
library(rvest)    # . Web Scraping Tools
library(ggplot2)  # . Data visualization
library(ggrepel)  # . For avoiding overlapping labels
library(progress) # . For progress bars
library(stringi)  # . For getting UTF8 codes out of char.'s
library(tidytext) # . For unnest_tokens() and other text manipulation
library(readr)    # . For read_csv()
library(forcats)  # . For easy reordering of bar charts
```

```{r Mapping_packages}
library(elevatr)
library(raster) # Along with elevatr, for making line maps
library(leastcostpath)
```

```{r Fixing_fonts_hopefully}
# Fix fonts?
library(ragg)
```

```{r Loading_map_data}
#| include: false
# Generate a data frame of lat/long coordinates.
#ex.df <- data.frame(x=seq(from=22.5, to=24.5, length.out=10), 
                    #y=seq(from=37.5, to=38.5, length.out=10))

# Specify projection.
#prj_dd <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
```

```{r Map_loading}
#| include: false
# Use elevatr package to get elevation data for each point.
#elev <- get_elev_raster(ex.df, prj = prj_dd, z = 14, clip = "bbox")

# Going to try removing negative values
#elev[elev<=-200] <- NA
```

```{r Load_enviro?}
# ABSOLUTELY FUCKING IMPERATIVE
# SAVE.IMAGE()
# SO THAT THE RASTER DATA IS SAVED TO AN ENVIRO .RDATA FILE
# QUARTO CANNOT HANDLE DOWNLOADING THAT MUCH ON RENDER
# IT WILL SHIT ITSELF INTO AN EARLY GRAVE DEAR GOD I CANNOT
# EMPHASIZE THIS ENOUGH
# LOAD
# RASTER
# DATA
# FROM
# .RDATA
# OR THIS WILL NOT WORK EVER
load("~/Documents/UGA/Thesis/.RData")
```

```{r Make_cities_df}

# Athens 37.972453603, 23.726268222
# Eleusis 38.041101, 23.537401

# Megara 37.985078, 23.340163
# Pagai 38.084923, 23.197116
# Aigosthena 38.1497606, 23.2294868

# Tanagra 38.3001983333, 23.581173
# Ororpus 38.3194635, 23.7899985
# Make DF of cities
cities <- tibble(x = c(23.726268222, 23.537401, 23.340163, 23.197116, 23.2294868, 23.581173, 23.7899985),
                 y = c(37.972453603, 38.041101, 37.985078, 38.084923, 38.1497606, 38.3001983333, 38.3194635),
                 names = c("Athens", "Eleusis", "Megara", "Pagai", "Aigosthena", "Tanagra", "Oropos"),
                 colors = c("#56B4E9", "#56B4E9", "#E69F00", "#E69F00", "#E69F00", "#009E73", "#009E73"))

```

```{r Reading_Unnested_Data}
UnnestedData <- read_csv(
  "~/Documents/UGA/Thesis/Wukia/data/UnnestedData.csv",
  col_types = cols(ig_book = col_factor(levels = c()),
                   location = col_factor(levels = c()),
                   Token = col_factor(levels = c())))
UnnestedData <- rename(UnnestedData, token = Token)
```

```{r Reading_Nested_Data}
NestedData <- read_csv(
  "~/Documents/UGA/Thesis/Wukia/data/NestData.csv",
  col_types = cols(ig_book = col_factor(levels = c()),
                   ig_no = col_factor(levels = c()),
                   location = col_factor(levels = c())))
```

    {{< include subfiles/Background.qmd >}}
    {{< include subfiles/Methodology.qmd >}}
    {{< include subfiles/Study.qmd >}}
    {{< include subfiles/Conclusions.qmd >}}

# References
::: {#refs}
:::

\includepdf[pages=1,pagecommand={\addcontentsline{toc}{chapter}{R Libraries}}]{lib_bib/lib_bib.pdf}
\includepdf[pages=2,pagecommand={}]{lib_bib/lib_bib.pdf}


```{=tex}
\begin{appendices}
```
    {{< include subfiles/Scraper.qmd >}}

\input{subfiles/CopyOfDGE.tex}

```{=tex}
\end{appendices}
```
