# Background

## The Geographical Arrangement of the Greek Dialects

The ancient Greek dialects were divided into two principal groups based on the retention of the inherited segment \textipa{*ti} (\textgreek{τι}) or the assibilation \textipa{*ti} \> \textipa{*si} (\textgreek{σι}). The third-person singular ending of present athematic verbs evidences this isogloss most consistently: Doric \textgreek{δίδωτι} '(s)he gives' vs. Attic \textgreek{δίδωσι}. When drawn on a map, notwithstanding some exceptions, the \textgreek{τι}/\textgreek{σι} isogloss line divided Attica from the rest of the Greek mainland and Ionia from the surrounding Greek dialects of Anatolia.

The North Greek family included the Aiolic and West Greek groups, including Laconian, Megarian, and the other Doric varieties. These dialects historically retained the segment \textipa{*ti} (\textgreek{τι}); however, Lesbian selected the assibilated \textipa{*si} (\textgreek{σι}) sometime before the alphabetic period via prolonged contact with Ionic. The West Greek dialects differentiated themselves from Aiolic by, for example, the extension of the future/aorist marker -\textgreek{ξ}- to all verbs with a present in -\textgreek{ζω} regardless of the underlying stem. For example, compare the Doric middle aorist infinitive \textgreek{ἐργαξάσθαι} 'to work' with the Attic cognate \textgreek{ἐργάσασθαι}. Additionally, the West Group innovated the 'Doric Future' -\textgreek{σέω} by blending the thematic future -\textgreek{σω} with the contract future -\textgreek{έω}. For example, Delphic \textgreek{κλεψέω} 'I will steal' and Heraclean \textgreek{ἐργαξῆται} '(s)he will work' vs.\ Attic \textgreek{κλέψω} and \textgreek{ἐργάσαται}, respectively.[@dosuna2015, 449] These dialects occupied the Peloponnese -- with the exception Arcadia -- Megaris, the stretch between Boiotia and Thessalia, and the mainland from the Ionian sea to the western slopes of the Pindos Mountains.

The Aiolic group saw frequent innovations along with selections from neighboring dialects, differentiating itself by such isoglosses as the development of Proto-Greek labiovelars into labials before front vowels: compare Thessalian \textgreek{πέμπε} 'five' to Attic \textgreek{πέντε}. Furthermore, the group developed the athematic dative plural ending -\textgreek{εσσι}, as seen in Lesbian \textgreek{\ladd{χρη{\WK}}μάτεσσι} 'money' corresponding to Attic \textgreek{χρήμασι}, and extended the endings -\textgreek{ων}, -\textgreek{οντος} to the perfect active participle in place of -\textgreek{ώς}, -\textgreek{ότος}. For example, Boiotian \textgreek{ϝεϝυκονομειόντων} 'having managed' corresponds to Attic \textgreek{ᾠκονομηκότων}, and  \textgreek{ἀπειλθείοντες} 'having departed' to \textgreek{ἀπεληλυθότες}.[@dosuna2015a, 461-2] This group occupied the countries of Thessalia and Boiotia on the western coast of the Ionian sea, as well as the island of Lesbos and the country of Aiolia on the northern-western coast of Anatolia.

The Southern Greek family included the Mycenaean, Arcado-Cypriot, and Attic-Ionic dialects. These dialects assibilated \textipa{*ti} (\textgreek{τι}) to \textipa{*si} (\textgreek{σι}) sometime before the Mycenaean period, as indicated by the Mycenaean do-so-si \textipa{/d\=osonsi/} 'they will give,' vs.\ Attic \textgreek{δώσουσι}.[@chadwick2015, 400] While the Mycenaean syllabary complicates any attempts at discerning Mycenaean isoglosses, orthographically adjacent vowels in such forms as do-e-ro \textipa{/doelos/} (Attic \textgreek{δοῦλος}) and e-ke-e \textipa{/ek\super{h}een/} (\textgreek{ἔχειν}) indicate a general lack of vowel contraction.[@chadwick2015, 396]

The Attic dialect differentiated itself primarily via two isoglosses. First, the dialect lost the bilabial glide at an early date: compare Attic \textgreek{οἰκία} 'home' with Boiotian \textgreek{ϝοικία}. Second, Attic-Ionic underwent an exclusive vowel shift, raising the long vowel \textgreek{ᾱ} to \textgreek{η}. As a result, where Doric inscriptions mention the \textgreek{βουλ\'ᾱ} 'council' and the \textgreek{δᾶμος} 'deme, people,' Attic inscriptions mention the \textgreek{βουλή} and the \textgreek{δῆμος}. Attic further differentiated itself from Ionic by two exclusive changes. First, Attic reversed the vowel change after \textgreek{ε}, \textgreek{ι}, or \textgreek{ρ}. For example, the \textipa{\=a}-stem ending is raised in the Ionic variant \textgreek{ἱστορίη} 'inquiry,' but lowered in the Attic \textgreek{ἱστορία}. Second, Proto-Greek clusters with a non-labial consonant and a palatal glide resulted in the geminate stop \textgreek{ττ} in Attic and the fricative \textgreek{σσ} in Ionic (and most other dialects): Attic \textgreek{πράττω} 'I do' and \textgreek{θάλαττα} 'sea' vs. Ionic \textgreek{πράσσω} and \textgreek{θάλασσα}. The Attic-Ionic dialect, defined by the raising of \textgreek{ᾱ} to \textgreek{η}, occupied the country of Attica, comprising the Attic Peninsula, Ionia on the western coast of Anatolia, Euboia, and the Cyclades.

The Arcado-Cypriot dialect is defined by differed by, among others, three basic isoglosses. First, the vowel \textgreek{ε} raised to \textgreek{ι}, most typically in proximity to a nasal consonant, as demonstrated by Arcado-Cyrpiot \textgreek{ἰν} 'in' vs. Attic \textgreek{ἐν}. Second, the vowel \textgreek{ο} raised to \textgreek{υ}, sometimes in proximity to a nasal consonant but most often word-finally. For example, cf.\ Arcado-Cypriot neuter \textgreek{ἄλλυ} 'other' vs. Attic-Ionic \textgreek{ἄλλο}. Finally, Arcado-Cypriot preferred the athematic suffix -\textgreek{ής} (also spelled -\textgreek{\'{ε̄}}\textgreek{ς}) over -\textgreek{εύς}, as is found in other dialects. For example, the Cypriot forms \textgreek{ἰϳερ\'{ε̄}}\textgreek{ς} 'priest' and \textgreek{βασιλ\'{ε̄}}\textgreek{ς} 'king,' as well as Arcadian \textgreek{φον\'{ε̄}}\textgreek{ς} 'murderer,' may be compared with Attic-Ionic \textgreek{ἱερεύς}, \textgreek{βασιλεύς}, and \textgreek{φονεύς}.[@panayotou2015, 420] Last, the Arcado-Cypriot dialect formed middle present and future tenses with -\textgreek{τοι} rather than -\textgreek{ται}, as seen in Cypriot \textgreek{κεῖτοι} '(s)he lies down' vs. Attic \textgreek{κεῖται}.[@panayotou2015, 421] The mediopassive ending -\textgreek{τοι} occurs elsewhere only in Mycenaean: e-u-ke-to \textipa{/euk\super{h}etoi/} '(s)he offers prayers' corresponding to Attic-Ionic \textgreek{εὔχεται}.[@chadwick2015, 400] The Arcado-Cypriot dialect occupied the region of Arcadia in the highlands of the central Peloponnese and the island of Cyprus.

## The Phonological Inventory of Proto-Indo-European

Proto-Indo-European as typically reconstructed contained 25 phonemic consonants: fifteen stops, one fricative, two nasals, two liquids, two semivowels, and three obscure consonants called laryngeals. Stops showed the broadest variety, having distinguished between at least three places of articulation, two voices, and two secondary articulations. The nasals, liquids, and semivowels -- collectively called resonants -- as well as laryngeals could all function as syllable nuclei, whereas the stops and fricatives could not.

The labial stops included voiceless \textipa{*p}, voiced \textipa{*b}, and voiced aspirated \textipa{*b\super{h}}, closely mirrored by the dental stops \textipa{*t}, \textipa{*d}, and \textipa{*d\super{h}}. The velar stops -- \textipa{*k}, \textipa{*g}, and \textipa{*g\super{h}} -- and the palatovelar stops -- \textipa{*\'k}, \textipa{*\'g}, and \textipa{*\'g\super{h}} -- maintained this pattern. Additionally, the velar series distinguished between "plain" velars and labiovelars, which included a labial coarticulation: \textipa{*k\super{w}}, \textipa{*g\super{w}}, \textipa{*g\super{wh}}. The only phonemic fricative, \textipa{*s}, could assimilate for voice when in a consonant cluster, as in \textipa{*nizd\'os} 'nest,' derived from the root \textipa{*sed-} 'sit.'

The reconstructed inventory contained six resonants: two nasals, two liquids, and two semivowels. The nasals included \textipa{*m} and \textipa{*n}, the liquids \textipa{*l} and \textipa{*r}, and the semivowels \textipa{*w} and \textipa{*y}. These, along with the three laryngeals -- \textipa{*h}\sub{1}, \textipa{*h}\sub{2}, and \textipa{*h}\sub{3} -- could function as syllabic nuclei. A ring diacritic below the resonant indicates syllabicity, as with the laryngeal in \textipa{*d\super{h}\r*h}\sub{1}\textipa{t\'os} 'placed,' from the root \textipa{*d\super{h}eh}\sub{1}\textipa{-}.

```{=tex}
\begin{table}[htbp]
\centering
\caption{Proto-Indo-European consonants. Note the placement of the laryngeals, which are organized for convenience and not to describe their articulation beyond their potential syllabicity.}
\label{tab:pie-consonants}
\begin{tabular}{@{}rcccccc@{}}
\toprule
               & Labial         & Dental                      & Palatal      & Palatovelar         & Velar               & Labiovelar            \\ \midrule
Voiceless Stop & \textipa{*p}   & \textipa{*t}                &              & \textipa{*\'k}      & \textipa{*k}        & \textipa{*k\super{w}} \\
Voiced Stop    & \textipa{*b}   & \textipa{*d}                &              & \textipa{*\'g}      & \textipa{*g}        & \textipa{*g\super{w}} \\
Aspirated Stop & \textipa{*b\super{h}} & \textipa{*d\super{h}} &  & \textipa{*\'g\super{h}} & \textipa{*g\super{h}} & \textipa{*g\super{wh}} \\
Fricative      &                & \textipa{*s}                &              &                     &                     &                       \\ \midrule
Laryngeal      &                &                             &              & \textipa{*h}\sub{1} & \textipa{*h}\sub{2} & \textipa{*h}\sub{3}   \\
Nasal          & \textipa{*m}   & \textipa{*n}                &              &                     &                     &                       \\
Liquid         &                & \textipa{*l}{ }\textipa{*r} &              &                     &                     &                       \\
Semivowel      & \textipa{*w}   &                             & \textipa{*y} &                     &                     &                       \\ \bottomrule
\end{tabular}
\end{table}
```
The phonological inventory also distinguished between seven and ten vowels across three heights: high, mid, and low. The high vowels \textipa{*i} and \textipa{*u}, as well as the rare low vowel \textipa{*a}, may or may not have also occurred as the long vowels \textipa{*\=\i}, \textipa{*\=u}, and \textipa{*\=a}. The fact that the collocation of \textsc{*VHC} (a vowel followed by a laryngeal and then a consonant) resulted in \textsc{*\={V}C} (a consonant after a long vowel) significantly impedes any attempt to reconstruct these long vowels as phonemic.

The mid vowels \textipa{*e} and \textipa{*o} certainly did have the long counterparts \textipa{*\=e} and \textipa{*\=o}, as necessitated by the ablaut system. The stem \textipa{*p\r*h}\sub{2}\textipa{ter-} 'father' clearly exemplifies this. The nominative singular \textipa{*p\r*h}\sub{2}\textipa{t\'=er} contains a long \textipa{*\=e}, whereas the vocative singular \textipa{*p\r*{\'h}}\sub{2}\textipa{ter} contains a short \textipa{*e} in the same environment, creating a minimal pair. The Greek avatars \textgreek{πατήρ} and \textgreek{πάτερ} reflect this distinction. The compound stem \textipa{*\r*h}\sub{1}\textipa{su-p\r*h}\sub{2}\textipa{tor-} 'born of a good father' shows a similar pattern, with the nominative \textipa{*\r*h}\sub{1}\textipa{sup\r*{\'h}}\sub{2}\textipa{t\=or} and the vocative \textipa{*\r*h}\sub{1}\textipa{sup\r*{\'h}}\sub{2}\textipa{tor}. The avatars \textgreek{εὐπάτωρ} and \textgreek{εὐπάτορ} again reflect this distinction.

```{=tex}
\begin{table}[htbp]
\centering
\caption{Proto-Indo-European vowels. Note the dubious long vowels in parentheses.}
\label{tab:pie-vowels}
\begin{tabular}{@{}llllll@{}}
\toprule
 &
  Front &
   &
   &
   &
  Back \\ \midrule
High &
  \textipa{*i}{ }\textipa{(*\=\i)} &
   &
   &
   &
  \textipa{*u}{ }\textipa{(*\=u)} \\
 &
   &
  \textipa{*e}{ }\textipa{*\=e} &
   &
  \textipa{*o}{ }\textipa{*\=o} &
   \\
Low &
   &
   &
  \textipa{*a}{ }\textipa{(*\=a)} &
   &
   \\ \bottomrule
\end{tabular}
\end{table}
```
## Proto-Indo-European to Attic Greek

### Stops

#### Labial and Dental Stops

The PIE labial and dental stops followed a relatively simple derivation into Attic Greek. The voiced and voiceless stops remained largely unchanged. Labial stops \textipa{*p} and \textipa{*b} were retained as \textgreek{π} and \textgreek{β}, as in \textgreek{πέτομαι} 'I fly' \< \textipa{*peth}\sub{2}\textipa{-} and \textgreek{βελτίων} 'better' \< \textipa{*bel-} 'strong.'[@beekes2016, s.v. \textgreek{{ }βέλτερος}] Dental stops \textipa{*t} and \textipa{*d} were similarly retained: from \textipa{*telh}\sub{2}\textipa{-}, \textgreek{τελαμών} 'strap,' and from \textipa{*h}\sub{3}\textipa{dont-}, \textgreek{ὀδούς} 'tooth.' The voiced aspirated stops \textipa{*d\super{h}} and \textipa{*b\super{h}} first devoiced to \textipa{*t\super{h}} and \textipa{*p\super{h}}, then were retained in Attic Greek, as in \textgreek{θετός} 'placed' \< \textipa{*d\super{h}\r*{h}}\sub{1}\textipa{t\'os} and \textgreek{φέρω} 'I bear' \< \textipa{*b\super{h}er-}.

#### Velars

The velar series, however, took a relatively complicated path. Greek being a centum language, the palatovelars \textipa{*\'k}, \textipa{*\'g}, and \textipa{*\'g\super{h}} first merged with the plain velars \textipa{*k}, \textipa{*g}, and \textipa{*g\super{h}} in all contexts. The plain, unaspirated velars then passed directly into Greek: compare \textgreek{κέλλω} 'I put to harbor' \< \textipa{*kel-} to \textgreek{κενός} 'empty' \< \textipa{*\'ken-}, and \textgreek{ἐγείρω} 'I awaken' \< \textipa{*h}\sub{1}\textipa{ger-} to \textgreek{γελάω} 'I laugh' \< \textipa{*\'gelh}\sub{2}\textipa{-}. As seen with dental and labial stops, voiced aspirated velars, both original and resulting from the centum merger, were retained as voiceless aspirates: \textgreek{στείχω} 'I walk' \< \textipa{*steyg\super{h}-}; \textgreek{χήν} 'goose' \< \textipa{*\'g\super{h}\'ans}.

The labiovelar series was consistently fronted, but with a conditioned variation depending on what followed. Before \textipa{*a} or \textipa{*o}, the unaspirated labiovelars \textipa{*k\super{w}} and \textipa{*g\super{w}} resulted in the labial stops \textgreek{π} and \textgreek{β}, respectively. For example, \textgreek{πότερος} 'which (of two)' \< \textipa{*k\super{w}oteros} and \textgreek{βοῦς} 'cow' \< \textipa{*g\super{w}\=ous}. However, \textipa{*k\super{w}} resulted in a dental stop when followed by a front vowel, as in \textgreek{τίς} 'who?' \< \textipa{*k\super{w}is} and \textgreek{τε} 'and' \< \textipa{*k\super{w}e}, while voiced \textipa{*g\super{w}} resulted in a dental only before \textipa{*e}: \textgreek{ἀδελφός} 'brother' \< \textipa{*s\r*{m}g\super{w}elb\super{h}os} vs. \textgreek{βίος} 'life' \< \textipa{*g\super{w}ih}\sub{3}\textipa{os}. Grammatical paradigms for stems ending in a labiovelar were leveled by analogy, with verbs adopting the stem consonant of the first-person singular, and nominals that of the nominative singular. Hence the third-person singular \textgreek{λείπει} '(s)he leaves behind' \< \textipa{*leyk\super{w}-}, standing in for \iform[G]{λείτει}; and the genitive singular \textgreek{ἔπεος} 'word' \< \textipa{*wek\super{w}-}, rather than \iform[G]{ἔτεος}. Labiovelars notably lost their labial coarticulation when following or preceding the vowel \textipa{*u} in a process called the Boukolos Rule. This change takes its name after the noun \textgreek{βουκόλος} 'cowherd' \< \textipa{*g\super{w}\=ou-k\super{w}ol-} which presents a medial \textgreek{κ} where a labiovelar would typically have returned a \iform[G]{π}, as exemplified in \textgreek{αἰπόλος} 'goatherd' \< \textipa{*ayg-k\super{w}ol-}. This rule took effect before the Mycenaean period: the inscription 51=An20 \[18\] from Pylos mentions 90 missing cowherds, spelled \textipa{qo-u-ko-ro /g\super{w}oukoloi/} with the secondary velar stop in the syllable \textipa{-ko-}.[@ventris2015, p. 182]

Voiced aspirated labiovelars were first devoiced in accordance with other aspirated stops. Similar to plain labiovelars, aspirated labiovelars developed a conditioned variation between labial, dental, and velar stops. Like plain voiced labiovelars, aspirated labiovelars fronted to a dental before \textipa{*e}, as in \textgreek{θείνω} 'I kill' \< \textipa{*g\super{wh}en-y\=o}. Before a non-front vowel or before \textipa{*i}, the result was a labial consonant, e.g., \textgreek{φόνος} 'murder' \< \textipa{*g\super{wh}on-} (o-grade from \textipa{*g\super{wh}en-}) and \textgreek{ὄφις} \< \textipa{*og\super{wh}is} 'serpent.'

The voiced aspirates were subject to the effects of Grassmann's law, which interfered with consecutive heterosyllabic aspirates. In these \*C\super{h}\dots C\super{h} conditions, the first aspirate lost its aspiration. That the resulting consonant remained voiceless indicates that the change occurred at least after the devoicing of aspirated stops. In reduplicated presents, the result is an unaspirated reduplicated syllable with an aspirated root onset, as in \textgreek{τίθημι} from \textipa{*d\super{h}i-d\super{h}eh}\sub{1}\textipa{-}. Some nominal stems alternate between C\super{h} \dots C\textgreek{ς} in the nominative singular or C\super{h} \dots C\textgreek{σιν} in the dative plural and C \dots C\super{h}- in the other case-number combinations, owing to the loss of aspiration in C\super{h}\textipa{s} clusters. For example, the underlying form \textipa{|t\super{h}rik\super{h}-|} 'hair' emerges as the nominative singular \textgreek{θρίξ} and dative plural \textgreek{θρίξιν}, but the accusative singular \textgreek{τρίχα} and genitive plural \textgreek{τριχῶν} show the full effect of Grassmann's law.

```{=tex}
\begin{table}[htbp]
\centering
\caption{Exemplary Labiovelar Outcomes. Source: Benjamin W. Fortson,\textit{Indo-European Language and Culture: An Introduction}, 2nd ed, Blackwell Text-books in Linguistics 19 (Chichester, U.K. ; Malden, MA: Wiley-Blackwell, 2010), 253}
\label{tab:labiovelar-outcomes}
\begin{tabular*}{1\textwidth}{@{\extracolsep{\fill}}lp{.3\textwidth}p{.3\textwidth}p{.3\textwidth}@{\extracolsep{\fill}}}
\toprule
 & Before \textipa{*e} & Before \textipa{*i} & Before C or back V                                                                         \\ \midrule
\textipa{*k\super{w}} &
  \textgreek{τε} `and' < \textipa{*k\super{w}e} &
  \textgreek{τίς} `who?' < \textipa{*k\super{w}is} &
  \textgreek{πότερος} `which?' < \textipa{*k\super{w}o-teros} \\
 &                     &                     & \textgreek{πέμπτος} `fifth' < \textipa{*penk\super{w}tos}          \\
\textipa{*g\super{w}} &
  \textgreek{ἀδελφός} `brother' < \textipa{*s\r*{m}-g\super{w}elb\super{h}os} &
  \textgreek{βίος} `life' < \textipa{*g\super{w}ih}\sub{3}\textipa{os} &
  \textgreek{βοῦς} `cow' < \textipa{*g\super{w}\={o}us} \\
 &                     &                     & \textgreek{βάλλω} `I throw' < \textipa{*g\super{w}\r*{l}-n\={o}} \\
\textipa{*g\super{wh}} &
  \textgreek{θείνω} `I kill' < \textipa{*g\super{wh}en-y\={o}} &
  \textgreek{ὄφις} `snake' < \textipa{*og\super{wh}is} &
  \textgreek{νήφω} `I go without drink' < \textipa{*ne-eg\super{wh}-\={o}} \\
 &                     &                     & \textgreek{φρήν} `midriff' < \textipa{*g\super{wh}r\={e}n}       \\ \bottomrule
\end{tabular*}
\end{table}
```
### Laryngeals and Resonants

#### Laryngeals

Sometime before the Proto-Greek period, the laryngeals \textipa{*h}\sub{1}, \textipa{*h}\sub{2}, and \textipa{*h}\sub{3} had "colored" adjacent \textipa{*e-}vowels by discernibly altering their quality. The vocalic result of a laryngeal-vowel segment is annotated as \textipa{a\super{x}}, meaning the vowel corresponding to \textipa{*h\sub{x}}: \textipa{a}\super{1} = e, \textipa{a}\super{2} = a, and \textipa{a}\super{3} = o.

A \*VHC collocation, with a post-vocalic, pre-consonantal laryngeal, resulted in Greek \textipa{\=a\super{x}}, exemplified by the triad \textgreek{τίθημι} 'I place' \< \textipa{*d\super{h}eh}\sub{1}\textipa{-}, \textgreek{ἵστᾱμι} 'I set up' (Doric) \< \textipa{*steh}\sub{2}\textipa{-}, and \textgreek{δίδωμι} 'I give' \< \textipa{*deh}\sub{3}\textipa{-}. Pre-vocalic \*HV had the same qualitative effect but without any lengthening, returning \textipa{a\super{x}} as in \textgreek{ἐστί} 'is' \< \textipa{*h}\sub{1}\textipa{es-}, \textgreek{ἄγω} 'drive' \< \textipa{*h}\sub{2}\textipa{e\'g-}, and \textgreek{ὄψομαι} 'I will see' \< \textipa{*h}\sub{3}\textipa{ek\super{w}-}.[@bubenik2017, p. 641]

#### Glides

The glide \textipa{*y} resolved in various ways depending on its position and the adjacent phonemes. First, when in initial position, the glide fortified into the Greek \textgreek{ζ}, as in \textgreek{ζυγόν} 'yoke' \< \textipa{*yug\'om}, with an initial \textipa{*y-} evidenced by Hittite \textit{iugan}, Sanskrit \textit{yugám}, and Latin \textit{iugum}.[@beekes2016, s.v. \textgreek{{ }ζυγόν}] Meanwhile, when the glide followed a laryngeal in an initial cluster, the segment \textipa{*h\sub{x}y-} resulted in Greek \textipa{/h-/}. Cognates to the relative pronoun \textgreek{ὅς} 'which' \< \textipa{*h\sub{x}yo-} retain the initial glide in various other languages, such as \textit{yá-} in Sanskrit, \textit{ya-} in Avestan, and \textit{yo-} in Celtic (extant in the Gaulish \textit{dugiionti-io} 'who serve').[@fortson2010, p. 144] Moreover, the word for 'liver,' \textgreek{ἧπαρ} \< \textipa{*h\sub{x}y\=ek\super{w}\r*{r}}, is cognate with Old Avestan \textit{y\=akar\textschwa} and Middle Persian \textit{\v{\j}akar} beside Sanskrit \textit{yák\textsubring{r}t} and Latin \textit{iecur},[@beekes2016, s.v. \textgreek{{ }ἧπαρ}] indicating both the presence of an initial \textipa{*-y-} in these stems as well as establishing the need for a laryngeal to condition the varying outcomes of that glide.[^background-1]

[^background-1]: It should be noted however, that, this laryngeal explanation is controversial in the absence of any other incontrovertible evidence that the forms in question began with laryngeals.

Next, \textipa{*y} resulted in various medial outcomes depending primarily on what preceded and secondarily on what followed. For example, when a vowel directly preceded the glide, its retention depended entirely on the following segment. An intervocalic glide elided entirely, as seen in \textgreek{τρεῖς} 'three' \< \textipa{*tr\'eyes} (\textipa{*trey-}). Here, the vowel \textgreek{-ει-} is a spurious diphthong, created by the contraction of \textgreek{ε-ε} which resulted from the glide's elision. The Aiolic and Severer Doric \textgreek{τρῆς} evidence this, as in these dialects \textgreek{ε-ε} contracted to \textgreek{η}.[@smyth2013, 59D.] Furthermore, Sanskrit \textit{tráya\d{h}} and attests to the presence of the intervocalic \textipa{*-y-}, which is also implicit in the adverb \textgreek{τρίς} 'thrice' corresponding to Sanskrit \textit{trí\d{h}}, the compounding element \textgreek{τρι-}, and various other formations derived from the $\emptyset$-grade \textipa{*tri-}.[@beekes2016, s.v. \textgreek{{ }τρεῖς}]

However, the glide remained as the second element of a diphthong when it occurred before a consonant and after a vowel, as in \textgreek{οἶδα} 'I know' \< \textipa{*woyd-}. When following a consonant, the glide \textipa{*y} underwent diverging processes. After a nasal or rhotic, the cluster underwent metathesis, creating a secondary diphthong. For example, the nasal cluster \textipa{*-ny-} metathesized in \textgreek{μέλαινα} 'black (f.)' \< \textipa{*melanya}, as did the rhotic cluster \textipa{*-ry-} in \textgreek{φθείρω} 'I destroy' \< \textipa{*d\super{h}g\super{wh}er-y\={o}},[@beekes2016, s.v. \textgreek{{ }φθείρω}] and in \textgreek{μοῖρα} 'portion' \< \textipa{*mor-ya}.[@fortson2010, p. 650] However, this metathesis failed to occur in the cluster \textipa{*ly}, which resulted in the geminate \textgreek{λλ} in Attic Greek. For example, the adjective \textgreek{ἄλλος} 'other' \< \textipa{*h}\sub{2}\textipa{el-yo-} demonstrates the resulting \textgreek{λλ}, with Latin \textit{alius}, Gothic \textit{aljis}, and Old Irish \textit{aile} all attesting to the presence of the glide \textipa{*-y-} in this formation. Moreover, the verb \textgreek{στέλλω} 'I dispatch, make ready' \< \textipa{*stel-y\={o}} attests to the same gemination. The derived noun \textgreek{στόλος} 'equipment' demonstrates that the root did not originally end in a cluster, while the Old Church Slavonic cognate \textit{po-stelj\k{o}} 'I spread out' attests to an original yod-present.[@beekes2016, s.v. \textgreek{{ }στέλλω}]

Finally, when the glide \textipa{*y} followed a stop, those \textipa{*}C\textipa{y} collocations underwent a series of changes known as the First and Second Greek Palatalizations. The First affected the apical stops \textipa{*t}, \textipa{*d} and \textipa{*t\super{h}} \< \textipa{*d\super{h}}, assibilating them into \textipa{*ts}, \textipa{*dz} and \textipa{*t\super{h}s}. If uninterrupted, these affricates resulted in an Attic \textgreek{σ}. For example, the verb \textgreek{σέβομαι} 'I shrink in awe of' \< \textipa{*tyeg\super{w}-} shows the assibilation of \textipa{*ty-} to \textgreek{σ-} in initial position, with the cluster evidenced by the Sanskrit cognate \textit{tyaj-} 'flee.' Additionally, the noun \textgreek{σῆμα} 'sign' \< \textipa{*d\super{h}yeh}\sub{2}\textipa{-}, cognate with the Sanskrit \textit{d\super{h}y\textacutemacron{a}-} 'thought,' demonstrates the same assibilation in aspirated clusters. The adjective \textgreek{μέσος} 'middle' \< \textipa{*med\super{h}yos} demonstrates that the shift also occurred medially, with the cluster \textipa{*-d\super{h}y-} evidenced by Sanskrit \textit{mád\super{h}ya-} and Latin \textit{medius}. Lastly, the construction of feminine participles indicates that the assibilation took place even when following another consonant. For example, take the masculine and feminine participles \textgreek{φέρων} and \textgreek{φέρουσα}, both from \textipa{*b\super{h}er-}. The masculine genitive \textgreek{φέροντος} reveals the full participial suffix \textgreek{-οντ-}, implying the original stem \textipa{*b\super{h}eront-}. Appending the feminine ending \textipa{*-y\r*{h}}\sub{2} would result in the process \textipa{*b\super{h}eronty\r*{h}}\sub{2} \> Proto-Greek \textipa{*p\super{h}erontsa} \> \textipa{*p\super{h}eronsa}, and finally \textgreek{φέρουσα} after the loss of the nasal in \textipa{*ns} and compensatory lengthening. This outcome emphasizes that the shift from \textipa{*ty} \> \textgreek{σ} generally occurred in any position.[@sihler2008, 196]

However, since the glide \textipa{*y} remained in the contemporaneous phonological inventory of Pre-Proto-Greek, and since the glide appeared in various derivational suffixes --- especially in \textipa{*-y\K\sfrac{e}{o}-} presents, first declensions in \textipa{*-y\u=a}, and comparatives in \textipa{*-y\=on} --- many secondary forms still bore a strong resemblance to their stem. For example, the comparative \textipa{*kres\=on} 'stronger' \< \textipa{*krety\=on} transparently resembled the positive \textipa{*kratus} 'strong' \< \textipa{*k\r*{r}tus}, as both maintained the basic underlying stem shape \textipa{|kr}VC\textipa{|}. Similarly, \textipa{*er\'es\=o} 'I row,' beside \textgreek{ἐρέτης} 'oarsman' and \textgreek{ἐρετμόν} 'oar,' would have been intuited by speakers to represent \textipa{*er\'ety\=o}. In such morphologically transparent forms, widespread analogical restorations reintroduced the glide \textipa{*y} after segments assibilated in the First Greek Palatalization.[@sihler2008, 197] From \textipa{*krety\=on} and \textipa{*er\'ety\=o}, for example, arose \textipa{*krets\=on} and \textipa{*er\'ets\=o}.[@sihler2008, 197-200]

Following the analogical restoration of the glide \textipa{*y} in various positions, the Second Greek Palatalization assibilated all Pre-Greek consonants in \*Cy clusters. There were three Proto-Greek outcomes, depending on the place and voicing of the palatalized consonants.

First, voiceless velars and dentals both resulted in Proto-Greek \textipa{*\v{c}\v{c}}. For example, the restored \textipa{*-ty-} in the comparative \textipa{*krety\=on} became Proto-Greek \textipa{*kre\v{c}\v{c}\={o}n}. Meanwhile, the aspirated \textipa{*-k\super{h}y-} in \textipa{*t\super{h}ak\super{h}y\={o}n} 'quicker,' comparative of \textgreek{ταχύς} 'quick' \< \textipa{*d\super{h}\r*{n}g\super{h}-}, and the plain \textipa{*-ky-} in \textipa{*p\super{h}ulaky\={o}} 'guard' merged in their outcome with \textipa{*ty}, becoming \textipa{*t\super{h}a\v{c}\v{c}\={o}n} and \textipa{*p\super{h}ula\v{c}\v{c}\={o}}, respectively. This voiceless affricate became Attic Greek \textgreek{-ττ-}, hence \textgreek{θάττων} and \textgreek{φυλάττω}.[@sihler2008, 197-99]

Second, voiced (labio)velars and dentals also merged, but into the voiced \textipa{*\v{\j}\v{\j}}.[@sihler2008, 198] In this way, from Pre-Greek \textipa{*pedyos} arose Proto-Greek \textipa{*pe\v{\j}\v{\j}os}. Similarly, PIE \textipa{*h\sub{x}ya\'{g}-y\K\sfrac{e}{o}-}, with the voiced velar cluster \textipa{*-\'{g}y}, resulted in the Proto-Greek \textipa{*ha\v{\j}\v{\j}-\sfrac{e}{o}-}.[@beekes2016, s.v. \textgreek{{ }ἅγιος}] This voiced affricate became Attic Greek \textgreek{ζ}, resulting in the adjective \textgreek{πέζος} and the verb \textgreek{ἅζομαι} 'I stand in awe.'[@sihler2008, 200] This created a merger with the result of an initial glide \textipa{*y-}. For example, the \textgreek{ζ-} in the proper noun \textgreek{Ζεύς} 'Zeus' developed from an initial \textipa{*dy-}, as evidenced by the Sanskrit cognate \textit{dyáu\d{h}} 'heaven/day.'[@beekes2016, s.v. \textgreek{{ }Ζεύς}] On the other hand, the \textgreek{ζ-} in \textgreek{ζυγόν} resulted from a bare \textipa{*y-}, as above.

Finally, the cluster \textipa{*p\super{(h)}y} partially assibilated to Proto-Greek \textipa{*p\v{c}}. For example, PIE \textipa{*klep-y\K\sfrac{e}{o}-} 'steal' yielded Proto-Greek \textipa{klep\v{c}-\sfrac{e}{o}-},[@sihler2008, 202] with a root-final labial evidenced by the future \textgreek{κλέψω} and the derived noun \textgreek{κλέπος}, besides the Latin cognate \textit{clep\=o} 'I steal.'[@beekes2016, s.v. \textgreek{{ }κλέπτω}] Additionally, the verb \textipa{*t\super{h}ap\super{h}-y\K\sfrac{e}{o}-} 'bury' became \textipa{*t\super{h}ap\v{c}-\sfrac{e}{o}-}. The related noun \textgreek{τάφος} attests to a root-final aspirated \textipa{*p\super{h}}, demonstrating the merger between the aspirated \textipa{*p\super{h}y} and the unaspirated \textipa{*py}. The resulting \textipa{*p\v{c}} then developed into Attic \textgreek{πτ}, forming the verbs \textgreek{κλέπτω} and \textgreek{θάπτω}.[@sihler2008, 202]

Additionally, before the Greek Palatalizations, Attic and the other South Greek dialects assibilated \textipa{*t} to \textgreek{σ} before a syllabic \textipa{*i}. For example, the derivational suffix \textipa{*-ti-} resulted in Attic \textgreek{-σις}, as seen in \textgreek{βάσις} \< \textipa{*g\super{w}\r*{m}-ti-} and \textgreek{πρόγνωσις} \< \textipa{*-\'{g}\r*{n}h}\sub{3}\textipa{-ti-}. Notably, this affected a change in the 3rd pl. ending \textipa{*-nti}, which assibilated to \textipa{*-nsi}, then yielded \textgreek{-σι} with compensatory lengthening of the preceding vowel. As a result, assibilated Attic verbs correspond to unassibilated Doric counterparts, as in \textgreek{φέρουσι} and \textgreek{φέροντι}.[@fortson2010, 256] However, a preceding \textipa{*s} prevented assibilation, leading to \textgreek{στι} collocations in such forms as \textgreek{ἐστί} and \textgreek{στίζω}.

#### Syllabic Laryngeals and Resonants

The PIE syllabic resonants developed in one of two ways, depending on their manner of articulation. Here a distinction arises between the treatment of liquid consonants and that of nasals, laryngeals, or glides.

The nasals \textipa{*\r*m} and \textipa{*\r*n} developed to a simple \textgreek{α} in all dialects of alphabetic Greek. This commonly occurs in the third declension accusative singular, as seen in \textgreek{πόδα} \< \textipa{*pod-\r*{m}}, and in the alpha privative, as in \textgreek{ἄφθιτον} \< \textipa{*\r*{n}-d\super{h}g\super{wh}itom}.[@fortson2010, p. 254] The syllabic laryngeals \textipa{*\r*h}\sub{1}, \textipa{*\r*h}\sub{2}, and \textipa{*\r*h}\sub{3} evolved similarly; however, in keeping with laryngeal coloring, the resulting vowel was \textipa{*a\super{x}}. The triad \textipa{*d\super{h}eh}\sub{1}\textipa{-}, \textipa{*steh}\sub{2}\textipa{-}, and \textipa{*deh}\sub{3}\textipa{-} once again exemplify this process well, here through their passive verbal adjectives: \textgreek{θετός} 'placed' \< \textipa{*d\super{h}\r*{h}}\sub{1}\textipa{-t\'o-}, \textgreek{στατός} 'set' \< \textipa{*st\r*{h}}\sub{2}\textipa{-t\'o-}, and \textgreek{δοτός} 'given' \< \textipa{*d\r*{h}}\sub{3}\textipa{-t\'o-}.[@fortson2010, p. 255] Pre-Greek speakers also vocalized word-initial laryngeals before a consonant,[@fortson2010, p. 63] and these too resulted in \textipa{a\super{x}}: \textgreek{ἔρεβος} 'darkness' \< \textipa{*\r*{h}}\sub{1}\textipa{reg\super{w}-}, \textgreek{ἀνήρ} 'man' \< \textipa{*\r*{h}}\sub{2}\textipa{n\'er-}, and \textgreek{ὄφελος} 'help' \< \textipa{*\r*{h}}\sub{3}\textipa{b\super{h}el-}.[@fortson2010, p. 255]

The glides \textipa{*y} and \textipa{*w} stood in allophony with their syllabic counterparts \textipa{*i} and \textipa{*u}, and they survived as such into Greek. Examples of syllabic \textipa{*y} occur in various ablauting forms, such as \textgreek{ἔλιπον} 'I left behind,' aorist of \textgreek{λείπω} \< \textipa{*leyk\super{w}-}. In a similar fashion, ablauting variants of a shared stem can reveal instances of the glide \textipa{*w} surviving as a syllabic nucleus into Greek. For example, cognates with \textgreek{ζυγόν} 'yoke' include \textgreek{ζεῦγος} 'pair, team' and \textgreek{ζεύγνυμι} 'I join,' both in the full grade. As such, \textgreek{ζυγόν} must descend from the $\emptyset$-grade, making the vowel \textgreek{υ} the result of the syllabified glide \textipa{*w}.

In contrast, the syllabic liquids \textipa{\r*{r}} and \textipa{\r*{l}} gained an anaptyctic vowel.[@fortson2010, p. 254] Attic typically utilizes an alpha, as in \textgreek{καρδίᾱ} 'heart' \< \textipa{*\'k\r*{r}d-} and \textgreek{πλατύς} 'wide' \< \textipa{*p\r*{l}th}\sub{2}\textipa{-u-}, but various dialects instead preferred an omicron, as in Cypriot \textgreek{κόρζα} 'heart.' Furthermore, as seen in \textgreek{καρδίᾱ} and \textgreek{πλατύς}, the placement of the anaptyctic vowel is not consistent, even within Attic-Ionic. Whereas Attic, for example, had in its lexicon \textgreek{καρδίᾱ}, Homeric Greek had \textgreek{κραδίη}, demonstrating the change \textipa{*\r*{r}} \> \textipa{ra} rather than \textipa{*\r*{r}} \> \textipa{ar}. The inconsistent mechanics of anaptyxis suggests that the syllabic liquids had survived into Proto-Greek.

### The Sibilant \textipa{*s}

Sometime before the Mycenaean period, the fricative \textipa{*s} generally debuccalized when non-final to \textipa{*h}, which then elided non-initially. Intervocalic \textipa{/h/} appears in Mycenaean inscriptions, as seen in KN 227 = Oe 127 \textipa{pa-we-a}\sub{2} \textipa{/parweha/}, corresponding to \textgreek{φάρεα} 'clothes,' a neuter \textgreek{-εσ-} stem.[@ventris2015, p. 322] The character \textipa{a}\sub{2} indicates the syllable \textipa{/ha/},[@ventris2015, p. 385] demonstrating that the shift from \textipa{*s} to \textipa{h} had already been completed. There exists the alternate spelling \textipa{pa-we-a} in KN 219 = L 594 without any evident aspiration.[@ventris2015, p. 319] However, Mycenaean scribes did not typically indicate \textipa{/h/}, as evidenced in KN 212 = L 641 \textipa{o-} for \textipa{/h\=o/} 'thus,' corresponding to Attic \textgreek{ὧδε} 'id.,'[@ventris2015, p. 317] and KN 283 = So0442 \textipa{a-mo-te} for \textipa{/harmote/} (dual) 'wheels.'[@ventris2015, p. 371] That the spelling \textipa{pa-we-a}\sub{2} indicates aspiration is an exception to the rule, suggesting that \textipa{/h/} underwent elision during the Mycenaean period.

Debuccalization also occurred in most clusters, turning \textipa{*}VR\textipa{s} and \textipa{*}V\textipa{s}R segments into \textipa{*}VR\textipa{h} and \textipa{*}V\textipa{h}R, respectively. However, in these instances, the preceding vowel underwent compensatory lengthening with the ultimate loss of the aspirate. For example, the verb \textgreek{φαίνω} 'I show' from the stem \textgreek{φαν-} takes the sigmatic aorist \textgreek{*ε-φαν-σα}: here, the cluster \textgreek{-ν-σ-} debuccalizes to \textgreek{-ν-h-}, then loses its aspirate, leaving the aorist \textgreek{ἔφηνα} 'I showed' The verb \textgreek{στέλλω} 'I send' from \textgreek{στελ-} shows the same process, with the aorist \textgreek{*ε-στελ-σα} appearing in Attic as \textgreek{ἔστειλα} 'I showed' Accordingly, \textgreek{εἰμί} 'am' from \textgreek{εσ-} demonstrates the same process in \textipa{*s}C clusters, with Attic \textgreek{εἰμί} 'I am' arising from \textgreek{*εσ-μι}.

However, specific \textipa{*s} clusters resisted debuccalization. Clusters with a voiceless stop notably retained the fricative, as in \textgreek{ἐστί} 'is,' \textgreek{σφέτερος} 'their own,' and \textgreek{ἔπραξα} 'I did,' the sigmatic aorist of \textgreek{πράττω} from the stem \textgreek{πρακ-}. Other verb forms, namely non-aorists, also retained the sigma. For example, the perfect middle \textgreek{πέφανσαι} 'you (sg.) have appeared' retained the cluster \textgreek{-ν-σ-} where \textgreek{ἔφηνα} did not. Other sigmatic derivations, such as abstract nouns in \textgreek{-σις} \< \textipa{*-ti- },[@smyth2013, 865.1] also retain their sigmas: \textgreek{ἀπόφανσις} 'declaration' and \textgreek{κάθαρσις} 'cleansing,' for example.

In addition, there exist some unique cases. First, medial \textipa{*-rs-} clusters become Attic \textgreek{-ρρ-}, as shown by the correspondence between Attic \textgreek{ἄρρην} 'male' and Ionic \textgreek{ἄρσην} 'id.' Next, geminate \textipa{*ss} resisted debuccalization but degeminated without compensatory lengthening.[@bubenik2017, p. 649] The plural dative of \textgreek{-εσ-} stems, for example, demonstrates the phenomenon well: Attic \textgreek{φάρεσιν} 'clothes' corresponds to Mycenaean \textipa{pa-we-si} 'id.' in MY 228 = Oe111 + 136,[@ventris2015, p. 322] showing the outcome \textgreek{-εσιν} from an earlier formation \textipa{*es-sin}.

### The Attic-Ionic Vowel Shift

Late in its development, the Attic-Ionic dialect underwent a unique vowel shift which raised the long vowel \textgreek{ᾱ} to \textgreek{η}, resulting in numerous forms unique to this group, such as \textgreek{μήτηρ} 'mother' and \textgreek{δῆμος} 'deme,' corresponding to the typical Doric forms \textgreek{μᾱ́τηρ} 'mother' and \textgreek{δᾶμος} 'deme.' However, Attic then innovated conditioned reversals of this change after the vowels \textgreek{ε} and \textgreek{ι}, as well as following the consonant \textgreek{ρ}. As such, where Ionic showed the forms \textgreek{νεηνίης} 'young man,' \textgreek{ὥρη} 'season' and \textgreek{ἱστορίη} 'inquiry,' Attic showed the variants \textgreek{νεᾱνίᾱς} 'young man,' \textgreek{ὥρᾱ} 'season' and \textgreek{ἱστορίᾱ} 'inquiry.' However, an intervening glide prevented this reversal, resulting in the Attic form \textgreek{κόρη} 'girl' \< \textipa{*korw\={a}}.
